print("Lo stato di verità della espressione 1 == 0 è:", 1 == 0)
print("Lo stato di verità della espressione 1 == 1 è:", 1 == 1)
print("Lo stato di verità della espressione 1 < 0 è:", 1 < 0)
print("Lo stato di verità della espressione 1 > 0 è:", 1 > 0)
print("Lo stato di verità della espressione uno > zero è:", 'uno' > 'zero')
print("Lo stato di verità della espressione 'Python' è:", bool("Python"))
print("Lo stato di verità della espressione '' è:", bool(""))
print("Lo stato di verità della espressione non 'Python' è:", bool(not "Python"))
print("Lo stato di verità della espressione 'Python' e '' è:", bool("Python" and ''))
print("Lo stato di verità della espressione 'Python' o '' è:", bool("Python" or ''))