# Generated by Django 5.2.8 on 2025-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='testo',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
