# Generated by Django 5.2.8 on 2025-12-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articolo_testo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Giornalista',
        ),
    ]
