# Generated by Django 5.2.8 on 2026-02-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoAccademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_inizio', models.IntegerField()),
                ('anno_fine', models.IntegerField()),
                ('stato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cfu', models.PositiveIntegerField()),
                ('anno_di_corso', models.PositiveIntegerField()),
                ('semestre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dipartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('codice_ssd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StatoEsame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatoIscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatoPrenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppelloEsame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_appello', models.DateField()),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('modalita', models.CharField(max_length=20)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.corso')),
            ],
        ),
        migrations.CreateModel(
            name='CorsoDiLaurea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('classe_laurea', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=10)),
                ('dipartimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.dipartimento')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ruolo', models.CharField(max_length=50)),
                ('dipartimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.dipartimento')),
            ],
        ),
        migrations.CreateModel(
            name='CommissioneEsame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appello', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.appelloesame')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.docente')),
            ],
        ),
        migrations.CreateModel(
            name='SessioneEsami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.annoaccademico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.tiposessione')),
            ],
        ),
        migrations.AddField(
            model_name='appelloesame',
            name='sessione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.sessioneesami'),
        ),
        migrations.AddField(
            model_name='corso',
            name='ssd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.ssd'),
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('corso_di_laurea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.corsodilaurea')),
            ],
        ),
        migrations.CreateModel(
            name='PianoDiStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_approvazione', models.CharField(max_length=30)),
                ('data_presentazione', models.DateField()),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.annoaccademico')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.studente')),
            ],
        ),
        migrations.CreateModel(
            name='VerbaleEsame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chiusura', models.DateField(blank=True, null=True)),
                ('firma_digitale', models.BooleanField(default=False)),
                ('appello', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.appelloesame')),
            ],
        ),
        migrations.CreateModel(
            name='CommissioneComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(max_length=50)),
                ('commissione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.commissioneesame')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.docente')),
            ],
            options={
                'unique_together': {('commissione', 'docente')},
            },
        ),
        migrations.CreateModel(
            name='Docenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolare', models.BooleanField()),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.annoaccademico')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.corso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.docente')),
            ],
            options={
                'unique_together': {('docente', 'corso', 'anno_accademico')},
            },
        ),
        migrations.CreateModel(
            name='OffertaFormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.annoaccademico')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.corso')),
                ('corso_di_laurea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.corsodilaurea')),
            ],
            options={
                'unique_together': {('corso_di_laurea', 'corso')},
            },
        ),
        migrations.CreateModel(
            name='PianoDiStudiDettaglio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=20)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.corso')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.pianodistudi')),
            ],
            options={
                'unique_together': {('piano', 'corso')},
            },
        ),
        migrations.CreateModel(
            name='Propedeuticita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corso_principale', to='u_exam_app.corso')),
                ('corso_propedeutico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corso_prerequisito', to='u_exam_app.corso')),
            ],
            options={
                'unique_together': {('corso', 'corso_propedeutico')},
            },
        ),
        migrations.CreateModel(
            name='PrenotazioneEsame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateField()),
                ('appello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.appelloesame')),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.statoprenotazione')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.studente')),
            ],
            options={
                'unique_together': {('studente', 'appello')},
            },
        ),
        migrations.CreateModel(
            name='IscrizioneAnnuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_immatricolazione', models.DateField()),
                ('anno_accademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.annoaccademico')),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.statoiscrizione')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.studente')),
            ],
            options={
                'unique_together': {('studente', 'anno_accademico')},
            },
        ),
        migrations.CreateModel(
            name='EsameSostenuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(blank=True, null=True)),
                ('lode', models.BooleanField(default=False)),
                ('data_registrazione', models.DateField(blank=True, null=True)),
                ('appello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.appelloesame')),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='u_exam_app.statoesame')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_exam_app.studente')),
            ],
            options={
                'unique_together': {('studente', 'appello')},
            },
        ),
    ]
